name = "Evodyne"
uuid = "26464aff-74f4-49af-ae22-d05160b06cbf"
keywords = ["evolution", "simulator"]
license = "MIT"
desc = "Evolutionary dynamics simulator"
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
